kirkstone-5.15.71-2.2.0: Align meta layers related to chromium
The meta-browser and meta-clang layers version were ahead
of NXP's imx-5.15.71-2.2.0 manifest, which this manifest
is based on, resulting in an error when building chromium
due to version mismatch:

ERROR: chromium-ozone-wayland-110.0.5481.77-r0 do_patch:
    Applying patch '0003-Disable-dri-for-imx-gpu.patch' on target directory 'build_xwayland/tmp/work/armv8a-mx8mp-fslc-linux/chromium-ozone-wayland/110.0.5481.77-r0/chromium-110.0.5481.77'
    CmdError('quilt --quiltrc build_xwayland/tmp/work/armv8a-mx8mp-fslc-linux/chromium-ozone-wayland/110.0.5481.77-r0/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0003-Disable-dri-for-imx-gpu.patch
    patching file content/gpu/BUILD.gn
    Hunk 1 succeeded at 8 (offset 1 line).
    Hunk 2 FAILED at 141.
    1 out of 2 hunks FAILED -- rejects in file content/gpu/BUILD.gn
    Patch 0003-Disable-dri-for-imx-gpu.patch does not apply (enforce with -f)

Align meta-browser and meta-clang with imx-5.15.71-2.2.0.

Signed-off-by: Alifer Moraes <alifer.m@variscite.com>